pipeline {
    agent {label 'linux-slave'}
    options {
        skipDefaultCheckout()
    }
    stages {
        stage ('Check out source code'){
            steps {
                git branch:'master',
                url: 'https://github.com/nguyenpc3/react-for-demo-1.git'
                sh 'ls -la'
            }
        }
        stage ('Install Independencies'){
            tools {nodejs 'nodejs 8.9.4'}
            steps{
                sh '''
                echo "installing..."
                npm install
                echo "Install independencies OK"
                ls -al
                '''
            }
        }
        stage ('Build'){
            steps {
                nodejs (nodeJSInstallationName: 'nodejs 8.9.4') {
                    sh 'echo "Building application..."'
                    sh 'npm run build'
                    sh 'echo "Buil application OK'
                    sh 'ls -al'
                }
            }
        }
        stage ('Test') {
            tools {nodejs 'nodejs 8.9.4'} 
            steps {
                sh 'echo "Run unit test"'
                sh 'npm test'
                sh 'echo "Run unit test OK par"'
                sh 'ls -al'
            }
        }
    }
}
